import { Card, Checkbox, ChoiceList, TextField } from "@shopify/polaris";
import React from "react";
import styles from "../styles/AutoBump.module.css";

const AutoBumpSettings = ({
  setIsDisableBtn,
  settingsInfo,
  setSettingsInfo,
}) => {
  const {
    skipDisplay,
    backup,
    prePurchase,
    postPurchase,
    discountAmount,
    discountType,
  } = settingsInfo;

  const handleChange = (value, field) => {
    setIsDisableBtn(false);
    setSettingsInfo({ ...settingsInfo, [field]: value });
  };

  return (
    <Card title="Auto Bumps Settings" sectioned>
      {/* start percentage radio button */}
      <div>
        <p className={styles.settingsSubtitle}>
          Select an option for Auto Bumps offers:{" "}
        </p>

        <ChoiceList
          name="offer"
          choices={[
            {
              label: "0% - only Manual Bumps will be shown to customers",
              value: "0%",
            },
            {
              label:
                "50% - half of the bumps shown to customers will be generated by the Computer (great for A/B testing!)",
              value: "50%",
            },
            {
              label: "100% - only Auto Bumps will be shown to customers",
              value: "100%",
            },
          ]}
          selected={skipDisplay}
          onChange={(value) => handleChange(value, "skipDisplay")}
        />
      </div>

      {/* End percentage radio button */}

      {/* start backup */}
      <div className={styles.backupDiv}>
        <p className={styles.backupParagraph}>Backup Offer setting: </p>
        <Checkbox
          label="Use Auto Bumps for Backup Offers"
          helpText="Show an Auto Bump automatically when none of the Manual Bumps match customer cart conditions"
          checked={backup}
          onChange={(value) => handleChange(value, "backup")}
        />
      </div>
      {/* end backup */}

      {/* start bump type */}
      <div className={styles.BumpTypeDiv}>
        <p>Select where Auto Bumps will be shown:</p>
        <Checkbox
          label="Pre-purchase (checkout)"
          helpText="Bumps presented on the checkout page will be automatically generated"
          checked={prePurchase}
          onChange={(value) => handleChange(value, "prePurchase")}
        />
        <Checkbox
          label="
        Post-purchase"
          helpText="Bumps presented on the post-purchase page will be automatically generated"
          checked={postPurchase}
          onChange={(value) => handleChange(value, "postPurchase")}
        />
      </div>

      {/* end bump type */}
      <div className={styles.discount}>
        <div>
          <TextField
            value={String(discountAmount)}
            onChange={(value) => handleChange(value, "discountAmount")}
            label="Add discount (post-purchase only)"
            placeholder="e.g..9.99 "
            type="number"
          />
        </div>
        <div>
          <ChoiceList
            choices={[
              {
                label: "Percentage",
                value: "percentage",
              },
              {
                label: "Fixed Amount",
                value: "fixed",
              },
            ]}
            selected={discountType}
            onChange={(value) => handleChange(value, "discountType")}
          />
        </div>
      </div>
    </Card>
  );
};

export default AutoBumpSettings;
